### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by martinhbramwell** [awatson1978/starrynight#1]
Following through the steps on the [StarryNight tool's web page](http://starrynight.meteor.com/) I have hit a snag. 

```
yourself@qtst:~/projects/helloworld$ starrynight -survey acceptance
Launching StarryNight.  Analyzing meteor environment...
Detected a meteor instance...
Launching nightwatch bridge...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

yourself@qtst:~/projects/helloworld$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
Your packages are at their latest compatible versions.

yourself@qtst:~/projects/helloworld$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

yourself@qtst:~/projects/helloworld$ npm --version
1.3.10
```

Any ideas?

**Comment by meonkeys** [comment]
I ran into this too. See `CONFIG_PREFIX` in https://github.com/awatson1978/starrynight/blob/master/bin/starrynight.js . Looks like a start at abstracting the npm `prefix` config variable. PR #3 should help.
